# Generated by Django 3.0.2 on 2020-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='colab',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notes',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
